### ISSUE TITLE
Cannot get it working properly

### ISSUE THREAD

**Issue by Mecanik** [pm2-hive/pm2-nginx#3]
Hi, I am trying to make this work, but I cannot seem to do it.
The module is installed and running, I setup hostname, port, path "/status", also nginx has the stub status on, but it`s currently displaying:

Active connections: 8 
server accepts handled requests
 30863 30863 33868 
Reading: 0 Writing: 1 Waiting: 7 

Wich is the normal stub status page of nginx, could you help me out please ?

Many Thanks

**Comment by Mecanik** [comment]
Well many thanks... for nothing.

**Comment by mouryaamit** [comment]
HI @Mecanik, 
     Help me to work it. I am having following config

```
user  root;
worker_processes  1;
error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;
pid        logs/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for" "$txid"';
    access_log  logs/access.log  main;
    sendfile        off;
    gzip  on;
    include /usr/local/nginx/sites-enabled/*;
}
```

and 

```
server {
    listen 3000;
    location /nginx_status {
        stub_status;
    }
}
```

but it return 404 for /nginx_status while other things work fine on same port
